/*
 * Copyright (c) 2026 Sishi
 * SPDX-License-Identifier: Apache-2.0
 *
 * Project: TinyMind
 *
 * A small fixed-weight ternary neural-network inference accelerator.
 *
 * Seven switches are treated as binary input features.
 * Three artificial neurons calculate scores in parallel:
 *
 *   A = AI-oriented
 *   H = Hardware-oriented
 *   C = Creative-oriented
 *
 * The eighth switch selects the display mode:
 *
 *   ui_in[7] = 0 : show the predicted class
 *   ui_in[7] = 1 : show the confidence margin from 0 to 9
 *
 * The weights are fixed in hardware and use three possible values:
 *
 *   +1 : the feature supports the class
 *    0 : the feature is ignored
 *   -1 : the feature works against the class
 *
 * This chip performs inference only. It does not train itself.
 */

`default_nettype none

module tt_um_example (
    input  wire [7:0] ui_in,    // Dedicated input switches
    output wire [7:0] uo_out,   // Seven-segment display outputs
    input  wire [7:0] uio_in,   // Bidirectional input path
    output wire [7:0] uio_out,  // Bidirectional output path
    output wire [7:0] uio_oe,   // Bidirectional output enable
    input  wire       ena,      // Design enable
    input  wire       clk,      // Unused: design is combinational
    input  wire       rst_n     // Unused: design is combinational
);

  /*
   * -----------------------------------------------------------------------
   * INPUT FEATURES
   * -----------------------------------------------------------------------
   *
   * ui_in[6:0] are the seven yes/no features.
   *
   * Suggested meanings:
   *
   *   ui_in[0] = Likes mathematics
   *   ui_in[1] = Likes programming
   *   ui_in[2] = Likes electronics
   *   ui_in[3] = Likes physics
   *   ui_in[4] = Likes data and patterns
   *   ui_in[5] = Likes building things
   *   ui_in[6] = Likes design and creativity
   *
   * ui_in[7] selects the display mode.
   */

  wire display_confidence;

  assign display_confidence = ui_in[7];


  /*
   * Convert every one-bit feature into an explicitly signed six-bit value.
   *
   * This prevents signed-width surprises during synthesis.
   *
   * Each feature becomes either:
   *
   *   6'sd0
   *   6'sd1
   */

  wire signed [5:0] x0;
  wire signed [5:0] x1;
  wire signed [5:0] x2;
  wire signed [5:0] x3;
  wire signed [5:0] x4;
  wire signed [5:0] x5;
  wire signed [5:0] x6;

  assign x0 = ui_in[0] ? 6'sd1 : 6'sd0;
  assign x1 = ui_in[1] ? 6'sd1 : 6'sd0;
  assign x2 = ui_in[2] ? 6'sd1 : 6'sd0;
  assign x3 = ui_in[3] ? 6'sd1 : 6'sd0;
  assign x4 = ui_in[4] ? 6'sd1 : 6'sd0;
  assign x5 = ui_in[5] ? 6'sd1 : 6'sd0;
  assign x6 = ui_in[6] ? 6'sd1 : 6'sd0;


  /*
   * -----------------------------------------------------------------------
   * FIXED TERNARY WEIGHTS
   * -----------------------------------------------------------------------
   *
   * These weights are demonstration weights.
   *
   * Later, they could be generated by a Python training program and copied
   * into this Verilog file.
   *
   * AI-oriented neuron:
   *
   *   Math        +1
   *   Programming +1
   *   Electronics  0
   *   Physics      0
   *   Data         +1
   *   Building     -1
   *   Creativity    0
   *   Bias         +1
   */

  wire signed [5:0] score_ai;

  assign score_ai =
      x0 +
      x1 +
      6'sd0 +
      6'sd0 +
      x4 -
      x5 +
      6'sd0 +
      6'sd1;


  /*
   * Hardware-oriented neuron:
   *
   *   Math        +1
   *   Programming  0
   *   Electronics +1
   *   Physics     +1
   *   Data         0
   *   Building    +1
   *   Creativity  -1
   *   Bias          0
   */

  wire signed [5:0] score_hardware;

  assign score_hardware =
      x0 +
      6'sd0 +
      x2 +
      x3 +
      6'sd0 +
      x5 -
      x6 +
      6'sd0;


  /*
   * Creative-oriented neuron:
   *
   *   Math         0
   *   Programming -1
   *   Electronics -1
   *   Physics      0
   *   Data         0
   *   Building    +1
   *   Creativity  +1
   *   Bias         +1
   */

  wire signed [5:0] score_creative;

  assign score_creative =
      6'sd0 -
      x1 -
      x2 +
      6'sd0 +
      6'sd0 +
      x5 +
      x6 +
      6'sd1;


  /*
   * -----------------------------------------------------------------------
   * CLASS SELECTION
   * -----------------------------------------------------------------------
   *
   * The neuron with the highest score becomes the prediction.
   *
   * Tie priority:
   *
   *   AI first
   *   Hardware second
   *   Creative third
   *
   * This guarantees deterministic behavior.
   */

  localparam [1:0] CLASS_AI       = 2'b00;
  localparam [1:0] CLASS_HARDWARE = 2'b01;
  localparam [1:0] CLASS_CREATIVE = 2'b10;

  reg [1:0] predicted_class;

  reg signed [5:0] winning_score;
  reg signed [5:0] second_score;

  always @(*) begin

    /*
     * Compare the three scores and also remember the second-highest score.
     *
     * The difference between these two values becomes the confidence margin.
     */

    if ((score_ai >= score_hardware) &&
        (score_ai >= score_creative)) begin

      predicted_class = CLASS_AI;
      winning_score   = score_ai;

      if (score_hardware >= score_creative)
        second_score = score_hardware;
      else
        second_score = score_creative;

    end else if (score_hardware >= score_creative) begin

      predicted_class = CLASS_HARDWARE;
      winning_score   = score_hardware;

      if (score_ai >= score_creative)
        second_score = score_ai;
      else
        second_score = score_creative;

    end else begin

      predicted_class = CLASS_CREATIVE;
      winning_score   = score_creative;

      if (score_ai >= score_hardware)
        second_score = score_ai;
      else
        second_score = score_hardware;

    end
  end


  /*
   * -----------------------------------------------------------------------
   * CONFIDENCE MARGIN
   * -----------------------------------------------------------------------
   *
   * Confidence margin:
   *
   *   winning score - second-highest score
   *
   * Examples:
   *
   *   Scores 5, 2, 1 -> margin 3
   *   Scores 4, 3, 0 -> margin 1
   *   Scores 2, 2, 1 -> margin 0
   *
   * This is not a percentage or probability.
   * It only shows how far ahead the winning class is.
   */

  wire signed [5:0] raw_margin;
  wire [3:0] confidence_digit;

  assign raw_margin = winning_score - second_score;

  /*
   * Clamp the displayed margin to one decimal digit.
   */

  assign confidence_digit =
      (raw_margin > 6'sd9) ? 4'd9 :
      raw_margin[3:0];


  /*
   * A prediction is considered close when the winner leads by zero or one.
   *
   * In class mode, the decimal point will turn on for a close prediction.
   */

  wire close_prediction;

  assign close_prediction = (raw_margin <= 6'sd1);


  /*
   * -----------------------------------------------------------------------
   * SEVEN-SEGMENT DISPLAY
   * -----------------------------------------------------------------------
   *
   * Assumed segment order:
   *
   *          a
   *        -----
   *     f |     | b
   *       |  g  |
   *        -----
   *     e |     | c
   *       |     |
   *        -----
   *          d
   *
   * segments[6:0] = {a, b, c, d, e, f, g}
   *
   * uo_out[7] is assumed to be the decimal point.
   * A logic 1 is assumed to turn a segment on.
   *
   * If Wokwi shows incorrect shapes, only these segment constants need
   * adjustment. The AI logic will not need to change.
   */

  localparam [6:0] SEG_0 = 7'b1111110;
  localparam [6:0] SEG_1 = 7'b0110000;
  localparam [6:0] SEG_2 = 7'b1101101;
  localparam [6:0] SEG_3 = 7'b1111001;
  localparam [6:0] SEG_4 = 7'b0110011;
  localparam [6:0] SEG_5 = 7'b1011011;
  localparam [6:0] SEG_6 = 7'b1011111;
  localparam [6:0] SEG_7 = 7'b1110000;
  localparam [6:0] SEG_8 = 7'b1111111;
  localparam [6:0] SEG_9 = 7'b1111011;

  localparam [6:0] SEG_A = 7'b1110111;
  localparam [6:0] SEG_H = 7'b0110111;
  localparam [6:0] SEG_C = 7'b1001110;


  /*
   * Generate the character for the predicted class.
   */

  reg [6:0] class_segments;

  always @(*) begin
    case (predicted_class)
      CLASS_AI:
        class_segments = SEG_A;

      CLASS_HARDWARE:
        class_segments = SEG_H;

      CLASS_CREATIVE:
        class_segments = SEG_C;

      default:
        class_segments = SEG_0;
    endcase
  end


  /*
   * Convert the confidence digit into a seven-segment pattern.
   */

  reg [6:0] confidence_segments;

  always @(*) begin
    case (confidence_digit)
      4'd0: confidence_segments = SEG_0;
      4'd1: confidence_segments = SEG_1;
      4'd2: confidence_segments = SEG_2;
      4'd3: confidence_segments = SEG_3;
      4'd4: confidence_segments = SEG_4;
      4'd5: confidence_segments = SEG_5;
      4'd6: confidence_segments = SEG_6;
      4'd7: confidence_segments = SEG_7;
      4'd8: confidence_segments = SEG_8;
      4'd9: confidence_segments = SEG_9;

      default:
        confidence_segments = SEG_0;
    endcase
  end


  /*
   * -----------------------------------------------------------------------
   * DISPLAY MODE MULTIPLEXER
   * -----------------------------------------------------------------------
   *
   * ui_in[7] = 0:
   *
   *   Show A, H, or C.
   *   Decimal point indicates a close prediction.
   *
   * ui_in[7] = 1:
   *
   *   Show the confidence margin from 0 to 9.
   *   Decimal point is off.
   */

  wire [6:0] displayed_segments;
  wire       displayed_decimal_point;

  assign displayed_segments =
      display_confidence ? confidence_segments : class_segments;

  assign displayed_decimal_point =
      display_confidence ? 1'b0 : close_prediction;

  assign uo_out = {displayed_decimal_point, displayed_segments};


  /*
   * -----------------------------------------------------------------------
   * UNUSED BIDIRECTIONAL PINS
   * -----------------------------------------------------------------------
   *
   * All bidirectional outputs are driven low.
   * Output enables are zero, so the pins remain configured as inputs.
   */

  assign uio_out = 8'b0000_0000;
  assign uio_oe  = 8'b0000_0000;


  /*
   * Mark intentionally unused inputs to prevent lint warnings.
   */

  wire _unused = &{
      ena,
      clk,
      rst_n,
      uio_in,
      1'b0
  };

endmodule

`default_nettype wire
